name: ticket_personagen
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  firebase_core: ^4.2.0
  firebase_database: ^12.0.3

flutter:

  uses-material-design: true

  assets:
  - assets/bruce.png
  - assets/oyama.png
  - assets/viktor.png